USE Test

GO

CREATE PROCEDURE GET_VALUE
 @ID INT,
 @DATE NVARCHAR(MAX),
 @VALUE INT = -1

AS

BEGIN 
 BEGIN TRY
  BEGIN TRANSACTION
   IF @ID = 100
   BEGIN				
    DELETE
    FROM KGN_COUNTER_VAL
    WHERE IDCOUNTER = 100 AND DATE != CONVERT(NVARCHAR, GETDATE(), 104)

    UPDATE KGN_COUNTER_VAL
    SET @VALUE = [VALUE] = [VALUE] + 1
    WHERE IDCOUNTER = @ID AND DATE = @DATE
				
    IF @@ROWCOUNT = 0
     BEGIN
      SET @VALUE = 1
      INSERT KGN_COUNTER_VAL([IDCOUNTER], [DATE], [VALUE])	
      VALUES(@ID, @DATE, @VALUE)
     END
   END

	IF @ID = 200
     BEGIN
      UPDATE KGN_COUNTER_VAL
      SET @VALUE = [VALUE] = [VALUE] + 1
      WHERE IDCOUNTER = @ID AND DATE = @DATE

      IF @@ROWCOUNT = 0
       BEGIN
        SET @VALUE = 1
        INSERT KGN_COUNTER_VAL([IDCOUNTER], [DATE], [VALUE])	
        VALUES(@ID, @DATE, @VALUE)
      END
   END

    IF @ID = 300
     BEGIN
      UPDATE KGN_COUNTER_VAL
      SET @VALUE = [VALUE] = [VALUE] + 1
      WHERE IDCOUNTER = @ID AND DATE LIKE '___' + SUBSTRING(@DATE, 4,11)

	  IF @@ROWCOUNT = 0
       BEGIN
        SET @VALUE = 1
		INSERT KGN_COUNTER_VAL([IDCOUNTER], [DATE], [VALUE])	
        VALUES(@ID, '01.' + SUBSTRING(@DATE, 4,11), @VALUE)
       END
     END

      IF @ID = 400
       BEGIN
        UPDATE KGN_COUNTER_VAL
        SET @VALUE = [VALUE] = [VALUE] + 1
        WHERE IDCOUNTER = @ID AND DATE LIKE '%' + SUBSTRING(@DATE, 7,11)

        IF @@ROWCOUNT = 0
         BEGIN
          SET @VALUE = 1
          INSERT KGN_COUNTER_VAL([IDCOUNTER], [DATE], [VALUE])	
          VALUES(@ID, '01.01.' + SUBSTRING(@DATE, 7,11), @VALUE)
         END
        END
   COMMIT TRANSACTION
    RETURN @VALUE	
  END TRY
  BEGIN CATCH
	ROLLBACK TRANSACTION
		RETURN ERROR_MESSAGE()
  END CATCH
END	